<?php

return [

    'ucenter' => [
        'blackListModel' => 'black_list',
        'domainModel'    => 'domain',
        'medalModel'     => 'h_medal',
        'medalLogModel'  => 'h_medal_log',
        'heedModel'      => 'heed',
        'memberModel'    => 'member',
        'oauthModel'     => 'oauth',
    ],
    'lottery' => [
        'dateModel'    => 'h_date',
        'lotteryModel' => 'h_lottery',
    ],
    'bbs'     => [
        'classModel'       => 'h_class',
        'favoritesModel'   => 'h_favorites',
        'itemModel'        => 'h_item',
        'likeModel'        => 'h_like',
        'likeReplyModel'   => 'h_like_reply',
        'predictModel'     => 'h_predict',
        'replyModel'       => 'h_reply',
        'topModel'         => 'top_', //top_201910
        'topBonusCfgModel' => 'top_bonus_cfg',
        'topBonusLogModel' => 'top_bonus_log',
    ],
    'app'     => [
        //模型名=》表明
        'activityModel'       => 'h_activity',
        'adModel'             => 'h_ad',
        'adClassModel'        => 'h_ad_class',
        'agentModel'          => 'h_agent',
        'agentLookModel'      => 'h_agent_look',
        'announcementModel'   => 'h_announcement',
        'bannerModel'         => 'h_banner',
        'checkinModel'        => 'h_checkin',
        'checkinLogModel'     => 'h_checkin_log',
        'classModel'          => 'h_class',
        'searchModel'         => 'h_search',
        'appIndexModel'       => 'app_index_', //app_index_5
        'periodModel'         => 'period_', //period_201900
        'topModel'            => 'top_', //top_201910
        'historyModel'        => 'history_', //history_2
        'historyBbsModel'     => 'history_bbs_', //history_bbs_0
        'configModel'         => 'h_config',
        'dataModel'           => 'h_data',
        'dataClassModel'      => 'h_data_class',
        'dataRecModel'        => 'h_data_rec',
        'defaultLookModel'    => 'h_default_look',
        'favoritesModel'      => 'h_favorites',
        'feedbackReplyModel'  => 'h_feedback_reply',
        'feedbackModel'       => 'h_feedback',
        'itemModel'           => 'h_item',
        'levelModel'          => 'h_level',
        'likeModel'           => 'h_like',
        'likeReplyModel'      => 'h_like_reply',
        'manageModel'         => 'h_manage',
        'msgModel'            => 'h_msg',
        'newsModel'           => 'h_news',
        'noticeModel'         => 'h_notice',
        'pageModel'           => 'h_page',
        'platformModel'       => 'h_platform',
        'platformMemberModel' => 'h_platform_member',
        'predictModel'        => 'h_predict',
        'topBonusCfgModel'    => 'top_bonus_cfg',
        'topBonusLogModel'    => 'top_bonus_log',
        'umengHistoryModel'   => 'umeng_history',
        'redrainConfigModel'  => 'h_redrain_config',
        'taskLogModel'        => 'task_log',
        'taskRuleModel'       => 'task_rule',
        'recommendModel'      => 'h_recommend',
        'redrainModel'        => 'h_redrain',
        'redrainLogModel'     => 'h_redrain_log',
        'redrainTimingModel'  => 'h_redrain_timing',
        'relationModel'       => 'h_relation',
        'replyModel'          => 'h_reply',
        'shareCodeModel'      => 'h_share_code',
        'stampModel'          => 'h_stamp',
        'startAdsModel'       => 'h_start_ads',
        'userGroupModel'      => 'h_user_group',
        'withdrawModel'       => 'h_withdraw',
        'withdrawSiteModel'   => 'h_withdraw_site',
    ],
    'cash'    => [
        'logModel' => 'log_',//log_201906
    ],
    'images'  => [
        'answerModel'          => 'h_answer',
        'answerFavoritesModel' => 'h_answer_favorites',
        'answerReplyModel'     => 'h_answer_reply',
        'classModel'           => 'h_class',
        'favoritesModel'       => 'h_favorites',
        'itemModel'            => 'h_item',
        'likeModel'            => 'h_like',
        'likeReplyModel'       => 'h_like_reply',
        'periodModel'          => 'h_period',
        'replyModel'           => 'h_reply',
        'searchModel'          => 'h_search',
        'treadModel'           => 'h_tread',
        'viewModel'            => 'h_view',
    ],
];
